### ISSUE TITLE
"Uncaught ReferenceError: report is not defined"

### ISSUE THREAD

**Issue by varunnayyar76** [cemerson/cordova-mediaplayer-core#2]
hi, i installed your plugin and now getting error
"Uncaught ReferenceError: report is not defined" source: file:///android_asset/www/cordova-mediaplayer.js (220) Check my code,may be i am doing something wrong
![code](https://cloud.githubusercontent.com/assets/8187451/5678356/7f6b5854-9817-11e4-9763-dcfc6eb6d5dd.png)

**Comment by cemerson** [comment]
Sorry for such a delay here, @varunnayyar! 

I'm betting you got around this (if not gave up) but to fix just create a dummy method somewhere named "report()" ... or if you don't already have a logging method you could grab the one from my common JS files here: https://github.com/cemerson/common/blob/master/global.js#L21-L43

If you grab mine, you'll need to also define a couple global JS vars:
- isPublicBuild (boolean)
- cordovaIsLoaded (boolean)
